version: "2"
services:
    node1:
        image: seaweedfs:1
        hostname: node1
        ports:
            - "9333:9333"
        volumes:
            - "/root/mutil-dataCenter/node1:/masterdata"
        entrypoint: /usr/bin/weed master -mdir="/masterdata" -ip=node1 -peers="node1:9333,node4:9334,node7:9335,node10:9336" -defaultReplication="110"
        container_name: node1
        links:
            - "node2:node2"
            - "node3:node3"
        networks:
            - mynet
    node4:
        image: seaweedfs:1
        hostname: node4
        ports:
            - "9334:9334"
        volumes:
            - "/root/mutil-dataCenter/node4:/masterdata"
        entrypoint: /usr/bin/weed master -mdir="/masterdata" -ip=node4 -peers="node1:9333,node4:9334,node7:9335,node10:9336" -defaultReplication="110" -port=9334
        container_name: node4
        links:
            - "node5:node5"
            - "node6:node6"
        networks:
            - mynet

    node7:
        image: seaweedfs:1
        hostname: node7
        ports:
            - "9335:9335"
        volumes:
            - "/root/mutil-dataCenter/node7:/masterdata"
        entrypoint: /usr/bin/weed master -mdir="/masterdata" -ip=node7 -peers="node1:9333,node4:9334,node7:9335,node10:9336" -defaultReplication="110" -port=9335
        container_name: node7
        links:
            - "node8:node8"
            - "node9:node9"
        networks:
            - mynet

    node10:
        image: seaweedfs:1
        hostname: node10
        ports:
            - "9336:9336"
        volumes:
            - "/root/mutil-dataCenter/node10:/masterdata"
        entrypoint: /usr/bin/weed master -mdir="/masterdata" -ip=node10 -peers="node1:9333,node4:9334,node7:9335,node10:9336" -defaultReplication="110" -port=9336
        container_name: node10
        links:
            - "node11:node11"
            - "node12:node12"
        networks:
            - mynet

    node2:
        image: seaweedfs:1
        hostname: node2
        container_name: node2
        ports:
            - "8080:8080"
        volumes:
            - "/root/mutil-dataCenter/node2:/volume"
        entrypoint: /usr/bin/weed volume -dir="/volume" -max=10 -mserver="node1:9333"  -ip=node2 -port=8080 -dataCenter="dc1" -rack="rack1"
        networks:
            - mynet

    node3:
        image: seaweedfs:1
        hostname: node3
        container_name: node3
        ports:
            - "8081:8081"
        volumes:
            - "/root/mutil-dataCenter/node3:/volume"
        entrypoint: /usr/bin/weed volume -dir="/volume" -max=10 -mserver="node1:9333"  -ip=node3 -port=8081 -dataCenter="dc1" -rack="rack1"
        networks:
            - mynet

    node5:
        image: seaweedfs:1
        hostname: node5
        container_name: node5
        ports:
            - "8082:8082"
        volumes:
            - "/root/mutil-dataCenter/node5:/volume"
        entrypoint: /usr/bin/weed volume -dir="/volume" -max=10 -mserver="node4:9334"  -ip=node5 -port=8082 -dataCenter="dc1" -rack="rack2"
        networks:
            - mynet

    node6:
        image: seaweedfs:1
        hostname: node6
        container_name: node6
        ports:
            - "8083:8083"
        volumes:
            - "/root/mutil-dataCenter/node6:/volume"
        entrypoint: /usr/bin/weed volume -dir="/volume" -max=10 -mserver="node4:9334"  -ip=node6 -port=8083 -dataCenter="dc1" -rack="rack2"
        networks:
            - mynet
    node8:
        image: seaweedfs:1
        hostname: node8
        container_name: node8
        ports:
            - "8084:8084"
        volumes:
            - "/root/mutil-dataCenter/node8:/volume"
        entrypoint: /usr/bin/weed volume -dir="/volume" -max=10 -mserver="node7:9335"  -ip=node8 -port=8084 -dataCenter="dc2" -rack="rack1"
        networks:
            - mynet
    node9:
        image: seaweedfs:1
        hostname: node9
        container_name: node9
        ports:
            - "8085:8085"
        volumes:
            - "/root/mutil-dataCenter/node9:/volume"
        entrypoint: /usr/bin/weed volume -dir="/volume" -max=10 -mserver="node7:9335"  -ip=node9 -port=8085 -dataCenter="dc2" -rack="rack1"
        networks:
            - mynet
    node11:
        image: seaweedfs:1
        hostname: node11
        container_name: node11
        ports:
            - "8086:8086"
        volumes:
            - "/root/mutil-dataCenter/node11:/volume"
        entrypoint: /usr/bin/weed volume -dir="/volume" -max=10 -mserver="node10:9336"  -ip=node11 -port=8086 -dataCenter="dc2" -rack="rack2"
        networks:
            - mynet
    node12:
        image: seaweedfs:1
        hostname: node12
        container_name: node12
        ports:
            - "8087:8087"
        volumes:
            - "/root/mutil-dataCenter/node11:/volume"
        entrypoint: /usr/bin/weed volume -dir="/volume" -max=10 -mserver="node10:9336"  -ip=node12 -port=8087 -dataCenter="dc2" -rack="rack2"
        networks:
            - mynet
networks:
    mynet:
        driver: bridge
